# Copyright (c) 2025 Navimatix GmbH
# SPDX-License-Identifier: Apache-2.0

name: Basic Twister Test

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  twister-tests:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: workflow_test
      - name: Zephyr Setup
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: workflow_test
          toolchains: x86_64-zephyr-elf
      - name: Debug Output
        run: |
          ls
          cd workflow_test
          ls
          cd ..
      - name: Run Test
        run: |
          west twister \
            -p native_sim \
            -T workflow_test/tests/drv8424 \
            --simulation native \
            -v \
            -x=CONFIG_ZTEST_SHUFFLE=y 
      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: twister-out/twister_report.xml
        if: always() # Also run if previous jobs failed

        
