# Copyright (c) 2025 Navimatix GmbH
# SPDX-License-Identifier: Apache-2.0

name: Workflow Test

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  test1:
    name: Test 1 Echo
    runs-on: ubuntu-24.04
    steps:
    - name: Step 1
      run: |
        echo "Step 1"
    
    - name: Step 2
      run: |
        echo "Step 2"

  test2:
    name: Test 2 Math
    runs-on: ubuntu-24.04
    steps:
    - name: Math
      run: |
        var=2+2; echo $var